# Codemagic configuration for the Bundly (Expo) project
# - This workflow runs EAS builds for Android and iOS on pushes to `main` (and PRs).
# - Set secure environment variables in Codemagic UI before using:
#     - EAS_TOKEN  (required) - your EAS CLI token
#     - EXPO_TOKEN (optional) - legacy Expo token if needed
#     - APPLE_ID and other Apple secrets if you plan to manage iOS credentials in CI
# - Adjust `EAS_BUILD_PROFILE` if you use other profiles in eas.json

workflows:
  build_eas:
    name: Build (EAS) Android & iOS
    triggering:
      events:
        - push
        - pull_request
    environment:
      # Import variable groups from Codemagic UI so secure vars (Application) are available
      groups:
        - Application
      # Node version used on the build VM
      node: "18.16.0"
      # Use default CocoaPods ; Codemagic will install CocoaPods on macOS runners
      cocoapods: default
      vars:
        # Change this to the profile name defined in your `eas.json` (e.g. production, preview)
        EAS_BUILD_PROFILE: production
        # NOTE: add secure vars (EAS_TOKEN, EXPO_TOKEN, APPLE_ID, etc.) in Codemagic UI
    scripts:
      - name: Checkout
        script: |
          # the repository is checked out by Codemagic automatically
          echo "Checked out ${CM_BRANCH} @ ${CM_SHA}"

      - name: Install dependencies
        script: |
          set -e
          # prefer lockfile install, fallback to legacy-peer-deps if needed
          if [ -f package-lock.json ]; then
            npm ci || npm install --legacy-peer-deps
          else
            npm install --legacy-peer-deps
          fi

      - name: Cache node_modules (optional)
        script: |
          echo "Caching node_modules to speed up subsequent builds"
          # Codemagic has caching configuration in the UI; leave this line as a marker
          true

      - name: Install global CLI tools
        script: |
          set -e
          npm install -g eas-cli@latest
          npm install -g expo-cli@latest || true
          eas --version || true

      - name: Set EXPO_TOKEN from secure EAS_TOKEN (or use existing EXPO_TOKEN)
        script: |
          set -e
          # Prefer EAS_TOKEN (secure variable) and fall back to EXPO_TOKEN if already provided.
          if [ -n "$EAS_TOKEN" ]; then
            export EXPO_TOKEN="$EAS_TOKEN"
            echo "EXPO_TOKEN set from secure EAS_TOKEN (will be used by eas/eas-cli)"
          elif [ -n "$EXPO_TOKEN" ]; then
            echo "EXPO_TOKEN already defined in environment; using existing value"
          else
            echo "EAS_TOKEN / EXPO_TOKEN is not set. Set EAS_TOKEN as a secure environment variable in Codemagic or define EXPO_TOKEN directly."
            exit 1
          fi

      - name: "Optional: run lint/tests"
        script: |
          set -e
          if npm run | grep -q "lint"; then
            npm run lint || true
          fi
          if npm run | grep -q "test"; then
            npm test || true
          fi

      - name: Prepare (optional prebuild)
        script: |
          set -e
          # If you use prebuild steps, run them here (e.g. generating assets)
          if [ -f ./scripts/prebuild.sh ]; then
            bash ./scripts/prebuild.sh
          fi

      - name: EAS build — Android
        script: |
          set -e
          echo "Starting EAS Android build (profile: $EAS_BUILD_PROFILE)"
          eas build --platform android --non-interactive --profile "$EAS_BUILD_PROFILE"

      - name: EAS build — iOS
        script: |
          set -e
          echo "Starting EAS iOS build (profile: $EAS_BUILD_PROFILE)"
          eas build --platform ios --non-interactive --profile "$EAS_BUILD_PROFILE"

    artifacts:
      - '**/*.apk'
      - '**/*.aab'
      - '**/*.ipa'

    # publishing removed: configure notifications in the Codemagic UI instead

# Notes for you:
# - Codemagic will run this YAML on its Linux/macOS runners; EAS builds are executed in the cloud,
#   so Codemagic will trigger EAS and the final binary/artifact will be available through EAS.
# - Ensure you **do not commit secrets** (EAS_TOKEN, APPLE_CERT, etc.) — add them as secure
#   environment variables in Codemagic project settings.
# - If you prefer building with Codemagic-native Android/iOS pipelines (without EAS), tell me
#   and I can provide an alternate `codemagic.yaml` that runs Gradle/Xcode builds directly.
